### ISSUE TITLE
Compass arrow does not work on Nexus 7 and Nexus 10 Tablets

### ISSUE THREAD

**Issue by mypapit** [kvirair/Compass-View#5]
Hello there, the compassview library example application does not seem to work under Nexus 7 and Nexus 10. I've discovered this while testing my app that peruse your library. 

At first I thought I've used your library wrongly (I've tested it against other phones), but finally discovered that the CompassView arrow really does not appear in Nexus 7 and Nexus 10 tablets.

**Comment by kvirair** [comment]
Hi! I check it.

But I really not enough time for this library, help will be appreciated :)

**Comment by mypapit** [comment]
I'll try to send patch if I found the fix. Thanks for responding!

On Thu, Jan 22, 2015 at 1:11 PM, Artemiy Garin <notifications@github.com>
wrote:

> Hi! I check it.
>
> But I really not enough time for this library, help will be appreciated :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kvirair/Compass-View-Library/issues/5#issuecomment-70972429>
> .
>



-- 
Personal Blog : http://blog.mypapit.net
Website : http://mypapit.net
Profile: http://www.perlis.uitm.edu.my/hafiz

Hamradio Callsign : 9W2WTF

Codes:
http://code.google.com/u/mypapit
