### ISSUE TITLE
Not displaying on android 6.0 

### ISSUE THREAD

**Issue by raghucse2010** [kvirair/Compass-View#6]
I have been using this since a month, it worked on all other operating systems except on 6.0 which i have recent found. Hoping you will fix this very soon.

**Comment by DavidJuanes** [comment]
Just guessing here but this might be an issue with the permissions to access to the compass sensor... Android 6.0 introduced a new way to handle permissions for applications and the user can manually give/take individual permissions.

**Comment by kvirair** [comment]
@DavidJuanes right. 
@raghucse2010 please, feel free to send pull request :)

https://developer.android.com/training/permissions/requesting.html

**Comment by kvirair** [comment]
Close issue, because better call permissions in app and not in library (this variant more flexible).
